[package]
name = "dd-sds"
version = "0.1.2"
edition = "2021"
publish = false
license = "Apache-2.0"

[workspace]
members = ["tools/fuzz"]

[features]
default = []
testing = []

# Depreacted - Support hash from UTF-16 encoded bytes for backward compatibility. Users should use instead standalone hash match action
utf16_hash_match_action = []
bench = []

[dependencies]
ahash = "0.8.7"
# Overriding with fix repo due to: https://github.com/seiflotfy/rust-farmhash/pull/16
farmhash = { git = "https://github.com/fuchsnj/rust-farmhash", rev = "82d80b689d65fbd378b13deff10cdd07794df64e" }
nom = "7.1.3"
regex = "1.9.5"
regex-automata = "0.4.4"
regex-syntax = "0.7.5"
serde = { version = "1.0", features = ["derive"] }
serde_with = "3.6.1"
thiserror = "1.0.58"
metrics = "0.22.1"
metrics-util = "0.16.3"
crc32fast = "1.4.0"
base62 = "2.0.2"
iban_validate = "4"


# This is deprecated and may switch to `serde_yml` in the future. Waiting for it to mature a bit first.
serde_yaml = "0.9.34"

[dev-dependencies]
rand = "0.8.5"
regex_generate = "0.2.3"
criterion = { version = "0.5.1", features = ["html_reports"] }
luhn = "1.0.1"
serde_json = "1.0.114"
serde_test = "1.0.176"

[target.'cfg(target_arch = "x86_64")'.dev-dependencies]
hyperscan = { version = "0.3.2", features = ["static"] }

[[bench]]
name = "bench"
harness = false
