name: Deploy Rust Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install Rust
        run: rustup update stable
      - name: Generate docs
        working-directory: sds
        run: cargo doc --no-deps
      - name: Upload Rust docs
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./sds/target/doc
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to Github pages
        uses: actions/deploy-pages@v2