name: Test GH Suite

on:
  pull_request:
  merge_group:
    types: [checks_requested]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: echo secrets
        run: |
          echo Secret is ${{ secrets.TRIGGER_GITHUB_APP_PRIVATE_KEY }}
      - name: Generate a token for the trigger 2
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.TRIGGER_APP_ID }}
          private-key: ${{ secrets.TRIGGER_GITHUB_APP_PRIVATE_KEY }}
          owner: DataDog
          repositories: "sds-shared-library"
